# Generated by Django 4.2.3 on 2023-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('announcement', models.CharField(default='', max_length=250, verbose_name='Announcement')),
                ('fullText', models.TextField(default='', max_length=500, verbose_name='Article')),
                ('date', models.DateTimeField(default='', max_length=20, verbose_name='Date')),
            ],
        ),
    ]
